project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "posts/**/*.md"
    - "!posts/2025-11-09-recipe-for-investment-policy-statement-with-perplexity 2/"

website:
  title: "Redwall Analytics"
  site-url: "https://redwallanalytics.com"
  favicon: static/images/redwall.png
  google-analytics: "UA-177379740-1"

  navbar:
    logo: static/images/redwall.png
    logo-alt: "Redwall Analytics"
    left:
      - text: "Posts"
        href: index.qmd
    right:
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
      - icon: linkedin
        href: "https://linkedin.com/in/david-lucey-cfa-mba-msba"
        aria-label: LinkedIn
      - icon: bluesky
        href: "https://bsky.app/profile/luceydav.bsky.social"
        aria-label: BlueSky
      - icon: github
        href: "https://github.com/luceydav"
        aria-label: GitHub

  page-footer:
    left: "© Redwall Analytics LLC 2018–2025"

format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: github
    toc: true
