baseURL = "https://www.redwallanalytics.com/"
languageCode = "en-gb"
title = "Redwall Analytics"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-177379740-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
disqusShortname = "www-redwallanalytics-com"

[permalinks]
    post = "/:year/:month/:day/:slug"
    
#[social]
	#github  = "luceydav"
	#twitter  = "lucey_david"

[menu]
    [[menu.main]]
    name = "Redwall Analytics"
    url = "/about/"
    weight = 1
    
    [[menu.main]]
    name = "About"
    pre = ""
    weight = 2
    url = "/about/"
    
    [[menu.main]]
    name = "Contact"
    pre = ""
    weight = 3
    url = "/contact/"
    
    [[menu.main]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/david-lucey-cfa-cpa-mba-msba"
    weight = 4
    
    [[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/lucey_david"
    weight = 5
    
    [[menu.main]]
    name = "GitHub"
    url = "https://github.com/luceydav"
    weight = 6
    
[params]
    description = ""

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "redwall.png"
    width = 50
    height = 50
    
    [params.copyright]
    #prefix = ""
    holder = "Redwall Analytics LLC"
    startYear = "2018"
    #suffix = ""
    
    #[params.sidebar]
    #enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
