[build]
command = "bash ./build.sh"
publish = "_site"

[build.environment]
QUARTO_VERSION = "1.8.27"

[[plugins]]
package = "netlify-plugin-quarto"

[context.branch-deploy]
command = "bash ./build.sh"

[context.deploy-preview]
command = "bash ./build.sh"
