[build]
command = "quarto render"
publish = "_site"
[build.environment]
QUARTO_VERSION = "1.4.557"

[context.branch-deploy]
command = "quarto render"

[context.deploy-preview]
command = "quarto render"

[context.production]
command = "quarto render"
