[build]
command = "quarto render"
publish = "_site"
[build.environment]
QUARTO_VERSION = "1.6.42"

[[plugins]]
package = "netlify-plugin-quarto"

[context.branch-deploy]
command = "quarto render"

[context.deploy-preview]
command = "quarto render"

[context.production]
command = "quarto render"
